name: quran_controller
description: Quran Controller that offering a Quran Verses With Quran font which is Called Uthmani script
version: 1.6.6
homepage: http://www.hassony.com

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  assets:
    - assets/fonts/
    - assets/surah/
    - assets/verses/
