name: quran_controller
description: Quran Controller Package
version: 0.0.4
homepage: https://www.google.com

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  assets:
    - lib/assets/fonts/
    - lib/assets/quran/

#  fonts:
#    - family: sura
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
